### ISSUE TITLE
Logger - running out of disk space.

### ISSUE THREAD

**Issue by omairvaiyani** [parse-community/parse-server#3403]
I kept running out of space on my AWS EC2 instance until I figured out that our code deployer was setting VERBOSE to 1. This kept crashing our server almost daily with ```ENOSPC```, until it was redeployed. Now that I've disabled verbose, and set ```logLevel``` to ```"error"```, I still think that we'll hit ```ENOSPC``` eventually. Is there a way to remove older logs?

To be honest, I want to completely disabled logging until I'm sure about this issue no longer being a problem. But I haven't figured out a simple way yet.

**Comment by codegefluester** [comment]
With the default logging it seems like you could simply clean-up the `./logs` folder yourself with a cronjob on the server. You could either delete log files, compress older ones or a mix of both. I didn't find a documented config for the Winston logger that would take care of it, but maybe someone else can help on that front https://github.com/winstonjs/winston#usage

**Comment by dplewis** [comment]
For those interested I'm also using AWS. I'm deleting my logs files using cronjobs. First I SSH into my parse-server instance and run the following commands.

Run cron on your box
`$ crontab -e`

Copy and Paste the following line
`$ 55 2 * * * sudo /usr/bin/find /var/app/current/logs/ -type f -mtime +2 -delete;`

Replace `/var/app/current/logs/` with the location of your logs. The command runs at 2:55AM and only keeps the last 3 days of logs.

**Comment by milesrichardson** [comment]
Also, if you're running in docker, and logging to stdout as well as log files, you might need to delete the docker log file for the container. Easiest way to clear it is like this:

``` bash
echo '' | sudo tee  "/var/lib/docker/containers/${CONTAINER_ID}/${CONTAINER_ID}-json.log"
```

**Comment by dplewis** [comment]
If you are using AWS you can create a config file that will install cornjobs when you create an instance.

`.ebextensions/cron.config`

```
files:
  "/etc/cron.d/parse-log-cleanup":
      mode: "000644"
      owner: root
      group: root
      content: |
        55 2 * * * root /usr/bin/find /var/app/current/logs/ -type f -mtime +2 -delete;

commands:
  remove_old_cron:
    command: "rm -f /etc/cron.d/*.bak"
```

Notice unlike my last comment this uses `root` instead of `sudo`
