### ISSUE TITLE
Assign Docker-Secrets with _FILE Environment Extension

### ISSUE THREAD

**Issue by a6b8** [parse-community/parse-server#5001]
I want to implement the `docker secrets` extension feature (`_FILE`) in parse server.  Here´s a small `docker-compose` example with a the latest mysql image:

<h4>Example</h4>
Without secrets:

```
version: '3.1'
services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: db_password
    [more services...]
volumes:
    db_data:
```

With secrets:
- Create secrets
```
printf "This is a secret" | docker secret create db_root_password -
printf "This is a secret" | docker secret create db_password -
```
- docker-compose.yml
```
version: '3.1'
services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_root_password
       - db_password
    [more services...]
secrets:
   db_password:
     external true
   db_root_password:
     external true
volumes:
    db_data:
```

Basically makes `docker secrets` only a file from the volume accessible for a container (in a secure way)- not more not less. The Idea is to tell the container where to find the `secret` and the container itself has the right to load the `secret`.

The most important adjustment is the `_FILE` Extension (eg. `MYSQL_ROOT_PASSWORD_FILE`). This trick makes the new feature backward compatible with the current Environment Variables. Docker has updated most of the official containers (mysql, wordpress etc...).

<h4>Load secret in nodejs</h4>
```
MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
```

```
  fs.readFile(process.env.MYSQL_ROOT_PASSWORD_FILE, (err, contents) => {
    if (err && err.code == 'ENOENT') {
      console.log(err);
    }
console.log(contents);
    res.send("Database password: " + contents);
  });
```

<h3>My  Goal is to write a function which assigns the docker secrets (in my case over 20) to the default enviroment variables.</h3>

***Psydo Code***
Environment
```
      [...]
      PARSE_SERVER_ENABLE_ANON_USERS: 0
      PARSE_SERVER_MASTER_KEY_FILE: /run/secrets/db_password
      PARSE_SERVER_MAX_UPLOAD_SIZE: 64mb
      PARSE_SERVER_MOUNT_PATH: '/v1'
      [...]
```

Function
```
Function {
    Get all process.env  - keys // Object.keys(process.env)
    Filter for "_FILE" >> to Array
    Loop Array (Example: PARSE_SERVER_MASTER_KEY_FILE = /run/secrets/db_password)
        var a = Load secret from File  // ("This is a secret")
        var b = key.substring(0, key.indexOf("_FILE)) // PARSE_SERVER_MASTER_KEY
        create process.env.options[b] = "" // process.env.PARSE_SERVER_MASTER_KEY = ""
        process.env.options[b] = a // process.env.PARSE_SERVER_MASTER_KEY = "This is a secret"
}
```

<h4>My Question</h4>
Where is the best Place to implement this function? It needs to execute ---before--- all the options functions been triggered

file: src/index.js ?

place: 
```
const _ParseServer = function(options: ParseServerOptions) {
  >>> HERE ???
  const server = new ParseServer(options);
  return server.app;
}
```
Thanks for the help!

[https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images
](https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images
)
