### ISSUE TITLE
Custom Authentication on Docker Container

### ISSUE THREAD

**Issue by AienTech** [parse-community/parse-server#6128]
So, as the title suggests, I'm looking for a way to integrate my own custom authentication service into parseserver, which is installed inside a docker container. This authentication is basically an OpenID implementation of KeyCloak

What I've been trying so far, was to search the internet, read the issues and other stuff to find out, how can I create it.

It seems that it doesn't matter what I do, at the end of each test, I get a `252 This authentication method is unsupported` error! (this happens even if I use `facebook`, `oauth`, `oauth2`, etc).

the docker-compose service looks like this:

```
    parse-server:
        image: parseplatform/parse-server
        ports:
            - "${SERVER_PORT}:1337"
        restart: "always"
        volumes:
            - ./server/parse/custom-auth:/parse-server/custom-auth
        depends_on: 
            - mongodb
        links:
            - mongodb:mongo
        environment:
            - PARSE_SERVER_APPLICATION_ID=${APP_ID}
            - PARSE_SERVER_MASTER_KEY=${MASTER_KEY}
            - PARSE_SERVER_DATABASE_URI=mongodb://mongo:${MONGO_PORT}/dev
            - PARSE_SERVER_START_LIVE_QUERY_SERVER=1
            - PARSE_SERVER_LIVE_QUERY={"classNames":${LIVE_QUERY_CLASSES}}
            - PARSE_SERVER_MOUNT_GRAPHQL=${GQL_API}
            - PARSE_SERVER_MOUNT_PLAYGROUND=${GQL_PLAYGROUND}
            - PARSE_SERVER_AUTH_PROVIDERS={"swwwan-mail-auth":{"module":"/parse-server/custom-auth/swwwan-mail-auth/index.js"}}
```

and the login/signup part:
```
export const loginWithParse = async (account: IUserColumnTypes) => {
	if (account.username === null || account.password === null) {
		throw "validation failed";
	}

	// @ts-ignore
	const loggedIn = await Parse.User.logInWith("facebook", {
		authData: {
			id: "",
			access_token: "",
		},
	});

	console.log({ loggedIn });

	//return await Parse.User.logIn(account.username, account.password);
};
```

just to test what I get for `loggedIn`, which won't be reached at ever.

Is there a way to make it work? probably I'm missing something here.

tnx
