### ISSUE TITLE
GraphQL auto schema findQuery is not generated for classes named in plural

### ISSUE THREAD

**Issue by BufferUnderflower** [parse-community/parse-server#6218]
### Issue Description

GraphQL auto schema gets generated only partially for classes named in plural.  `get` seems to work fine, but `findQuery` is not available at all.

### Steps to reproduce
Create a collection named in plural, eg `Data`, `UserData`, `Comments` etc
 
### Expected Results
Be able to issue find GQL query 

### Actual Outcome

Schema generated only partially

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.9.0

### Logs/Trace
n/a

I understand this is a bad practice to name collection in plural (i have some legacy code), but for sure it's possible to handle by adding a few lines of code in generator for such edge cases. (when `pluralize`'s output equals `className`)

I'm looking forward to add a PR for that but i'm not sure what would be a better way to name it. `commentses` / `comments_`  / `commentss`  /  ... ?

**Comment by Moumouls** [comment]
Hummm strange
Could provide a screenshot of your `GraphQL Playground` ?
A raw parser server should show these queries

![Capture d’écran 2019-11-15 à 21 40 27](https://user-images.githubusercontent.com/27959372/68974332-c6f96500-07f0-11ea-93ad-f005394e4234.png)

**Comment by Moumouls** [comment]
Yes if your collection is named in plural the `Parse GraphQL Server` could not auto generate the plural version

I will take a look to our plural generation to check if we can add an auto renaming (plural to single) on plural classes

**Comment by BufferUnderflower** [comment]
> Yes if your collection is named in plural the `Parse GraphQL Server` could not auto generate the plural version
> 
> I will take a look to our plural generation to check if we can add an auto renaming (plural to single) on plural classes

I think 'depluralizing' won't work in 100% cases. Linguistic approach should be 'best effort' for nice readability rather a strict rule. There are other languages and letters combinations that will mislead english 'pluralizer' causing unexpected behavior. In case when pluralize `input==output` some fallback behavior is needed. Seems adding an extra symbol and checking the result against already established collection names is necessary to be on a safe side.

**Comment by Moumouls** [comment]
@BufferUnderflower  thanks for the PR ! 😄 
Can we close this one?

**Comment by nasermirzaei89** [comment]
_Pardon me opening closed issue_

How can I use auto schema for dockerized parse and prevent this message:
`Query ${fieldName} could not be added to the auto schema because it collided with an existing field.`

**Comment by Moumouls** [comment]
Hi @nasermirzaei89, what is your parse classes names ?

**Comment by nasermirzaei89** [comment]
> Hi @nasermirzaei89, what is your parse classes names ?

Media

**Comment by Moumouls** [comment]
You only have on class into your app ?
Your class media should be generated correctly, the result will be media and medias .
The issue seems to be more deeper.

Are you sure to run the latest version of the parse docker image ?

Can you provide your command line / config that you use to start the server ?

**Comment by nasermirzaei89** [comment]
the problem is when the auto schema generates. for example for `Item` class, list method will be items and findById will be item. but for `Media` class those are the same, so there will be a conflict when autoschema wants to add list items. both are `media`.
there are more words in English that plural is the same as the singular.
there should be a way that is compatible with docker envs to set custom names for graphql queries, maybe.

```yml
server:
    image: parseplatform/parse-server:4.2.0
    ports:
      - 1337:1337
    depends_on:
      - mongo
    environment:
      PARSE_SERVER_APPLICATION_ID: appId
      PARSE_SERVER_MASTER_KEY: masterKey
      PARSE_SERVER_DATABASE_URI: mongodb://mongo/xonyagar
      PARSE_SERVER_JAVASCRIPT_KEY: javascriptKey
      PARSE_SERVER_REST_API_KEY: restApiKey
      PARSE_SERVER_MAX_UPLOAD_SIZE: 100mb
      PORT: 1337
      PARSE_SERVER_HOST: 0.0.0.0
      PARSE_SERVER_MOUNT_PATH: /parse
      PARSE_SERVER_MOUNT_GRAPHQL: 1
      PARSE_PUBLIC_SERVER_URL: http://localhost:1337/parse
```
