### ISSUE TITLE
[Wiki] No "applicationId" option in LiveQuery Protocol Specification

### ISSUE THREAD

**Issue by JeffGuKang** [parse-community/parse-server#6481]
### Issue Description

There is a no "applicationId" option in [LiveQuery Protocol Specification](https://github.com/parse-community/parse-server/wiki/Parse-LiveQuery-Protocol-Specification)

```
{
  "op": "connect",
  "restAPIKey": "",  // Optional 
  "javascriptKey": "", // Optional
  "clientKey": "", //Optional
  "windowsKey": "", //Optional
  "masterKey": "", // Optional
  "sessionToken": "", // Optional
  "installationId": "" // Optional
}
```

When I tried socket load test, it was not connected without `applicatoinId`.

### Steps to reproduce
```artillery run test.yml```

test.yml

```
config:
  target: "http://127.0.0.1:1337/parse"

  phases:
    - duration: 60
      arrivalRate: 10
scenarios:
  - engine: "ws"
    flow:
      - send:
          op: "connect"
          applicationId: "tt" # Mandatory option if parse server has it
      - think: 1
      - send: "world"
      - think: 60 # do nothing for 1m and disconnect
```

### Expected Results

```
{
  "op": "connect",
  "applicationId": "",
  "restAPIKey": "",  // Optional 
  "javascriptKey": "", // Optional
  "clientKey": "", //Optional
  "windowsKey": "", //Optional
  "masterKey": "", // Optional
  "sessionToken": "", // Optional
  "installationId": "" // Optional
}
```
