### ISSUE TITLE
Email field in _Users is not unique preventing upgrade to 3.5.0

### ISSUE THREAD

**Issue by ArMouReR** [parse-community/parse-server#6638]
In our server email field is not unique. This is intentional behavior that was implemented a few years ago in order to host on the same db and server multiple Apps.
The only unique field is username that contains App id as part of the string.

Parse server on init trying to create email_1 index with following parameters:
db.getCollection("_User").createIndex( { "email": 1 }, {name: "email_1", sparse: true, background: true, unique: **true** } )

In our case we need to change unique: to **False**.

Can you please guide me how to change the code to remove this enforcement ?

Can it be added as feature request if someone else also interested in this feature ?
I am ready to work on PR...

Thanks !!!

- **Server**
  - parse-server version 2.3.7 moving to 3.5.0
  - Operating System:     Amazon Linux
  - AWS

- **Database**
  - MongoDB version: 4.2
  - Storage engine:  wiredTiger
  - AWS

### Logs/Trace
errmsg: 'Index with name: email_1 already exists with different options'

**Comment by davimacedo** [comment]
Unique email index has been in place since Parse 2.3.0 and there is a guide [here](https://github.com/parse-community/parse-server/blob/ade5a33c272b4a87a38b2a8ab91df2e0ff1cba4e/2.3.0.md). I believe it was something planned by design. I don't know exactly the reason and I'm not sure if a PR turning this index optional is a good idea. Maybe @acinader can help here.

**Comment by santiagosemhan** [comment]
It's not a common case to have not unique emails. Maybe If it turns optional, it could lead to security bugs.

**Comment by ArMouReR** [comment]
Can we make it part of configuration ?  e.g. by default it will be turned on, but can be disabled in case that someone need it ?

**Comment by davimacedo** [comment]
At a first glance I don't see any problem in turning it optional.

**Comment by ArMouReR** [comment]
Does it needed for anyone except me ?

Meanwhile as I am running on AWS elastic beanstalk, so, I am posting here a quick hack that I did, just in case that any one will land here from Google:


This file should be placed inside .ebextensions:
remove_uniqueness_check_for_email.config
```
files:
  "/tmp/remove_uniqueness_check_for_email.sh":
    mode: "000755"
    owner: root
    group: root
    content: |
      #! /bin/bash
      # Loading environment data
      # EB_APP_CURRENT_DIR='/var/app/current/'
      # Remove uniqueness check for email column in _Users table
      # Multi line match
      # https://unix.stackexchange.com/questions/264344/how-to-replace-a-multi-line-code-with-sed
      # sed "/const\semailUniqueness/,/\})\;/{          # in this range
      # /.*/d                    			# delete all characters
      # }' infile                       
      find ./node_modules/parse-server/ -name 'DatabaseController.js'  -exec sed -i "/const\semailUniqueness/,/\})\;/{/.*/d}" {} +
      find ./node_modules/parse-server/ -name 'DatabaseController.js'  -exec sed -i "s/emailUniqueness,//g" {} +
container_commands:
  01remove_unneeded_file:
    command: "sh /tmp/remove_uniqueness_check_for_email.sh"
```
These two sed call are patching DatabaseController.js by removing call to ensureUniqueness  on email column.
