### ISSUE TITLE
Add simple example for docker-compose

### ISSUE THREAD

**Issue by ZebNoid** [parse-community/parse-server#7793]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
Hard to config docker compose for [parseplatform/parse-server](https://hub.docker.com/r/parseplatform/parse-server). 
No documentation on environment variable with examples.
No simple example of config file for parse server.
There is no mention that if cloud path is not set in config or  `PARSE_SERVER_CLOUD` variable cloud code wouldn't work.

### Feature / Enhancement Description

Add simple docker compose exmple.

### Example Use Case

Simple `docker-compose.yml` config
```yaml
version: "3.9"

networks:
  backend:
    name: backend

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.data-db:/data/db
    networks:
      - backend

  parse:
    image: parseplatform/parse-server:latest
    container_name: server
    ports:
      - "1337:1337"
    depends_on:
      - mongo
    volumes:
      - ./cloud-code:/parse-server/cloud
      - ./config/parse-config.json:/parse-server/config/parse-config.json
    entrypoint: ["node", "./bin/parse-server", "./config/parse-config.json"]
    networks:
      - backend

  dashboard:
    image: parseplatform/parse-dashboard:latest
    container_name: dashboard
    ports:
      - "4040:4040"
    environment:
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
    volumes:
      - ./config/parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json
    networks:
      - backend
```

Simple config file for parse server `parse-config.json` [Parse server options](http://parseplatform.org/parse-server/api/master/ParseServerOptions.html)
```json
{
    "appId": "yourappid",
    "masterKey": "yourmasterkey",
    "databaseURI": "mongodb://mongo:27017/dev",
    "cloud": "./cloud/main.js",
    "startLiveQueryServer": true,
    "liveQuery":
    {
        "classNames":
        [
            "Todo"
        ]
    },
    "push":
    {
        "android":
        {
            "senderId": "<firebase_cloud_messaging_sender_id>",
            "apiKey": "<firebase_cloud_messaging_server_key>"
        }
    }
}
```

Simple config for parse dashboard `parse-dashboard-config.json`
```json
{
  "apps": [
    {
      "serverURL": "http://localhost:1337/parse",
      "appId": "yourappid",
      "masterKey": "yourmasterkey",
      "appName": "ParseApp"
    }
  ],
  "users":
  [
    {
      "user":"admin",
      "pass":"pass"
    }
  ]
}

```

### Alternatives / Workarounds

All  environment variable can be found here [Definitions.js](https://github.com/parse-community/parse-server/blob/alpha/src/Options/Definitions.js) but there is no wiki page or mention of this file.

### 3rd Party References

n/a
