### ISSUE TITLE
Server checks null field (email) for uniqueness resulting Account already exists for this email address.

### ISSUE THREAD

**Issue by 2shrestha22** [parse-community/parse-server#8160]
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Server checks null field for uniqueness. When creating user with null email field more than once it gives `Account already exists for this email address.`

### Steps to reproduce

Create a user with null field multiple time.
```
curl -X POST \
-H "X-Parse-Application-Id: SECRET_APP_ID" \
-H "X-Parse-REST-API-Key: undefined" \
--data-urlencode "{\"username\": \"username1\", \"password\": \"password\", \"email\": null}" \
http://localhost:1337/parse/classes/_User
```
```
curl -X POST \
-H "X-Parse-Application-Id: SECRET_APP_ID" \
-H "X-Parse-REST-API-Key: undefined" \
--data-urlencode "{\"username\": \"username2\", \"password\": \"password\", \"email\": null}" \
http://localhost:1337/parse/classes/_User
```
### Actual Outcome

```
{
    "code": 202,
    "error": "Account already exists for this username."
}
```

### Expected Outcome

User should be created without issue when email field is null. `null` value on nullable field should not be checked to be unique.

### Environment

Arch Linux
docker-compose-yml
```
version: "3.9"
services:
  mongo-db:
    image: mongo:5.0.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  parse-server:
    image: parseplatform/parse-server:5.2.5
    ports:
      - "1337:1337"
    environment:
      - PARSE_SERVER_APPLICATION_ID=SECRET_APP_ID
      - PARSE_SERVER_MASTER_KEY=SECRET_MASTER_KEY
      - PARSE_SERVER_DATABASE_URI=mongodb://admin:admin@mongo/parse_server?authSource=admin
    links:
      - mongo-db:mongo
    volumes:
      - config-vol:/parse-server/config
      - cloud-code-vol:/parse-server/cloud

  parse-dashboard:
    image: parseplatform/parse-dashboard:4.2.0-alpha.4
    ports:
      - "4040:4040"
    command: --dev
    environment:
      - PARSE_DASHBOARD_SERVER_URL=http://localhost:1337/parse
      - PARSE_DASHBOARD_APP_ID=SECRET_APP_ID
      - PARSE_DASHBOARD_MASTER_KEY=SECRET_MASTER_KEY
      - PARSE_DASHBOARD_APP_NAME=TestApp
      - PARSE_DASHBOARD_USER_ID=admin
      - PARSE_DASHBOARD_USER_PASSWORD=admin

volumes:
  config-vol:
  cloud-code-vol:
```

Server
- Parse Server version: `5.2.5`
- Operating system: `Arch Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.0.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `REST-API/ParseDashboard`
- SDK version: `REST-API`
