### ISSUE TITLE
GraphQL logOut query dose not work 

### ISSUE THREAD

**Issue by Vildnex** [parse-community/parse-server#8257]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
I am trying to do a logout of a user via a GraphQL query, but is not working as expected.

### Steps to reproduce
After reading the documentation from [here](https://www.back4app.com/docs/parse-graphql/graphql-login) it showed that the query for login is like this:

```
mutation Login($username: String!="a", $password: String!="b") {
    logIn(input: {
        username: $username
        password: $password
    }){
        viewer{
            sessionToken
        }
    }
}

```
Afterward, the user will be login on to the server and I will have a new session added:

![image](https://user-images.githubusercontent.com/10352059/197402374-80540e68-aa04-4d24-8c4c-2b654014d257.png)

But my problem arises when I have when I am trying to do a logout query. So based also on this [documentation](https://www.back4app.com/docs/parse-graphql/graphql-logout-mutation) the logout query should look something like this:

```
mutation Logout($clientId: String!) {
    logOut(input: { clientMutationId: $clientId}) {
        ok
    }
}
```

So far as I understood the **clientMutationId** should be the objectID from the user (I am not 100% sure), so I've tried the following 

- **ObjectID of Session:** r5zqQngLHT 
- **ObjectID of User:** dCv5FiGtRw
- **Session Token:** r:8b8bdde1b8a5314a5a90ae8a47639864

None of the inputs worked and in all of the cases the session of my user remained open, and in all of the cases the output from this query was like this:

```
{
  "data": {
    "logOut": {
      "ok": true
    }
  }
}
```
Even in the case where clientMutationId is empty "". Did I understand it wrong? How should I log out of my user GraphQL if the version is not working?

GraphQL

### Environment
**I use a docker-compose.yaml**
```
version: '3.9'

services:
  database:
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ${HOME}/_DOCKER_DATA_/database:/data/db

  server:
    restart: always
    image: parseplatform/parse-server:5.2.8
    ports:
      - 1337:1337
    environment:
      - PARSE_SERVER_APPLICATION_ID=COOK_APP
      - PARSE_SERVER_APPLICATION_NAME=COOK_NAME
      - PARSE_SERVER_MASTER_KEY=MASTER_KEY_1
      - PARSE_SERVER_CLIENT_KEY=CLIENT_KEY_1
      - PARSE_SERVER_DATABASE_URI=mongodb://admin:admin@mongo/parse_server?authSource=admin
      - PARSE_SERVER_URL=http://10.0.2.2:1337/parse
      - PARSE_SERVER_MOUNT_GRAPHQL=true
    links:
      - database:mongo
    volumes:
      - ${HOME}/_DOCKER_DATA_/server:/data/server

  dashboard:
    image: parseplatform/parse-dashboard:5.0.0-beta.1
    ports:
      - "4040:4040"
    depends_on:
      - server
    environment:
      - PARSE_DASHBOARD_APP_ID=COOK_APP
      - PARSE_DASHBOARD_MASTER_KEY=MASTER_KEY_1
      - PARSE_DASHBOARD_USER_ID=admin
      - PARSE_DASHBOARD_USER_PASSWORD=admin
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
      - PARSE_DASHBOARD_SERVER_URL=http://localhost:1337/parse
      - PARSE_DASHBOARD_GRAPHQL_SERVER_URL=http://localhost:1337/graphql
    volumes:
      - ${HOME}/_DOCKER_DATA_/dashboard:/data/dashboard

```

Am I missing something?
