### ISSUE TITLE
DNS Resolution Problem with Traefik and Parse Server

### ISSUE THREAD

**Issue by davidmottet** [parse-community/parse-server#9498]
Hello everyone,

I'm experiencing an issue with the configuration of Traefik and Parse Server. I've set up Traefik to route requests to my Parse server, but I'm receiving a `DNS_PROBE_POSSIBLE` error and sometimes a timeout when trying to access my service via the domain name.

**Configuration Details:**

- **Traefik Version:** v3.2.1
- **Parse Server Version:** latest
- **Domain Name:** `parseserver.myurl.com`
- **Traefik Entrypoint:** `websecure` on port 443
- **SSL Certificate:** Configured with Let's Encrypt via `myresolver`
- **Routing Rule:** `Host(`parseserver.myurl.com`)`
- **Middleware:** HTTP to HTTPS redirection

**What I've Checked:**

1. Traefik logs do not show any obvious errors.
2. The SSL certificate seems to be correctly configured.
3. DNS is set up to point to my server's IP address.
4. Ports 80 and 443 are open on the server.
5. I tested direct access to the IP, but the issue persists.

**Logs and Error Messages:**

- Deprecation warning in Parse Server logs: `DeprecationWarning: The Parse Server option 'encodeParseObjectInCloudFunction' default will change to 'true' in a future version.`
- HTTP 200 response when accessing `http://172.28.0.3:1337/parse/health` directly from within the Docker network.

**Traefik Configuration:**
```yaml
services:
  traefik:
    image: traefik:v3.2.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=contact@myurl.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - /var/docker-volumes/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker-volumes/traefik/logs/traefik:/logs
```

**Docker Compose Configuration:**

```yaml
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db

  parse-server:
    image: parseplatform/parse-server:latest
    container_name: parse-server
    environment:
      - PARSE_SERVER_DATABASE_URI=mongodb://mongo:27017/foo
      - PARSE_SERVER_APPLICATION_ID=foo
      - PARSE_SERVER_MASTER_KEY=
      - PARSE_SERVER_FILE_KEY=
      - PARSE_SERVER_URL=http://parse-server:1337/parse
      - PARSE_SERVER_PUBLIC_SERVER_URL=https://parseserver.myurl.com/parse
      - PARSE_SERVER_CORS_ALLOW_ORIGIN=
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.parseserver.rule=Host(parseserver.myurl.com)"
      - "traefik.http.routers.parseserver.entrypoints=websecure"
      - "traefik.http.routers.parseserver.tls.certresolver=myresolver"
      - "traefik.http.services.parseserver.loadbalancer.server.port=1337"
      - "traefik.http.routers.parseserver.middlewares=redirect-to-https"

  parse-dashboard:
    image: parseplatform/parse-dashboard:latest
    container_name: parse-dashboard
    environment:
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
      - PARSE_DASHBOARD_CONFIG={"apps":[{"appId":"foo","serverURL":"https://parseserver.myurl.com/parse","masterKey":"","appName":"foo"}],"users":[{"user":"admin","pass":"bar"}]}
    depends_on:
      - parse-server

volumes:
  mongo-data:
```

**Questions:**

- Has anyone encountered this issue before?
- Are there additional steps I should check?
- Any suggestions to resolve this DNS problem?

Thank you in advance for your help!
